"""NSE 4 / FortiGate Administrator (FortiOS 7.x) practice questions.

MCQ entries:   (question, [options...], explanation) - prefix correct options with "*".
               Several "*" options make it a "choose N" question.
True/False:    (statement, True|False, explanation)
Text between backticks is rendered as code.
"""

MODULES = [
("System & Network Settings", [
    ("What is the default IP address of port1/mgmt on most new FortiGate devices?",
     ["*192.168.1.99/24", "192.168.1.1/24", "10.0.0.1/24", "192.168.0.99/24"],
     "Most FortiGate models ship with 192.168.1.99/24 on port1 or the mgmt port."),
    ("Which CLI command resets a FortiGate to factory defaults but keeps interface and VDOM settings?",
     ["*`execute factoryreset2`", "`execute factoryreset`", "`execute reboot`", "`execute formatlogdisk`"],
     "`factoryreset2` keeps interfaces and VDOMs; `factoryreset` wipes everything."),
    ("How do you recover a lost admin password on a hardware FortiGate?",
     ["*Log in on the console with user `maintainer` shortly after a reboot",
      "Use the `admin` account with password `fortinet`",
      "Hold the reset button for 30 seconds",
      "Connect through HTTPS on port 8443"],
     "Within ~60 s after a reboot, log in on the console as `maintainer` with password `bcpb` + serial number (if the maintainer account is enabled)."),
    ("Which two administrator profiles exist by default? (Choose two)",
     ["*`super_admin`", "*`prof_admin`", "`read_only`", "`global_admin`"],
     "`super_admin` has full access and can't be modified; `prof_admin` has full access inside its VDOM."),
    ("What is the default administrator idle timeout?",
     ["*5 minutes", "10 minutes", "15 minutes", "30 minutes"],
     "`config system global` → `set admintimeout` (default 5)."),
    ("Where do you allow HTTPS, SSH or PING access to the FortiGate itself?",
     ["*In the interface's Administrative Access settings", "In a firewall policy to the local interface",
      "In the admin profile", "In System > FortiGuard"],
     "Management protocols are enabled per interface with `set allowaccess`."),
    ("Which statement about interface roles (LAN, WAN, DMZ, Undefined) is correct?",
     ["*They only change which options the GUI shows for the interface",
      "They change how traffic is routed",
      "They automatically create firewall policies",
      "WAN role enables NAT automatically"],
     "Roles only simplify the GUI (e.g. hide the DHCP server on WAN); forwarding is not affected."),
    ("Which command manually triggers a FortiGuard update?",
     ["*`execute update-now`", "`diagnose autoupdate versions`", "`execute fortiguard-update`", "`get system fortiguard`"],
     "`diagnose autoupdate versions` only shows the current versions."),
    ("Trusted hosts on an administrator account restrict which source IPs can log in with that account.", True,
     "They limit where the admin can log in from; it is a key hardening step."),
    ("A configuration backup can be encrypted with a password, and the same password is needed to restore it.", True,
     "Encrypted backups also include sensitive data such as private keys."),
    ("You can upgrade FortiOS directly to any newer version without following an upgrade path.", False,
     "Always follow the supported upgrade path (Upgrade Path Tool) or configuration may be lost."),
    ("A VLAN interface on FortiGate is an 802.1Q sub-interface of a physical interface.", True,
     "Each VLAN interface has its own IP, VLAN ID and is used in policies like any interface."),
    ("A zone lets you group interfaces and block or allow traffic between its members with one setting.", True,
     "Intra-zone traffic is controlled by `set intrazone allow|deny`."),
]),

("Firewall Policies", [
    ("How does FortiGate choose which firewall policy applies to a new session?",
     ["*The first matching policy from the top of the list (by sequence)",
      "The policy with the lowest policy ID",
      "The most specific matching policy",
      "The last matching policy"],
     "Policies are evaluated top-down by sequence; the first match is used."),
    ("What is the ID of the implicit deny policy?",
     ["*0", "1", "999", "65535"],
     "Traffic that matches no policy is dropped by policy ID 0."),
    ("Which three fields are match criteria of a firewall policy? (Choose three)",
     ["*Incoming and outgoing interface", "*Source address or user", "*Service", "Security profile", "Log setting"],
     "Match criteria: interfaces, source, destination, service, schedule. Profiles and logging are actions/options."),
    ("What does the Internet Service Database (ISDB) provide?",
     ["*Known IPs, ports and protocols of public services such as Microsoft 365",
      "A list of local users",
      "IPS signatures",
      "URL categories for web filtering"],
     "ISDB objects replace destination address + service in a policy."),
    ("A policy has 'Log Allowed Traffic: Security Events'. What is logged?",
     ["*Only sessions that triggered a security profile event", "All sessions", "Nothing", "Only denied sessions"],
     "Select 'All Sessions' to log every allowed session."),
    ("Which GUI tool shows which policy a given flow will match?",
     ["*Policy Lookup", "FortiView", "Security Rating", "Packet Capture"],
     "Enter interface, protocol, source, destination and port to find the matching policy."),
    ("Which inspection mode buffers the whole file before scanning?",
     ["*Proxy-based", "Flow-based", "Certificate inspection", "Transparent"],
     "Proxy-based rebuilds content first: more features, more latency and memory."),
    ("In NGFW policy-based mode, where are applications and URL categories configured?",
     ["*Directly in security policies", "In security profiles only", "In the ISDB", "In the SSL inspection profile"],
     "Policy-based mode uses SSL inspection & authentication policies plus security policies with apps/URL categories."),
    ("What is the default session TTL?",
     ["*3600 seconds", "300 seconds", "600 seconds", "86400 seconds"],
     "It can be tuned globally, per service or per policy."),
    ("Which command shows only sessions from 10.0.1.10?",
     ["*`diagnose sys session filter src 10.0.1.10` then `diagnose sys session list`",
      "`get system session 10.0.1.10`",
      "`diagnose debug flow filter addr 10.0.1.10`",
      "`show firewall session src 10.0.1.10`"],
     "Clear the filter afterwards with `diagnose sys session filter clear`."),
    ("The policy ID determines the order in which policies are evaluated.", False,
     "The sequence (position in the list) decides order; the ID is only an identifier."),
    ("Traffic denied by the implicit deny policy is logged by default.", False,
     "Enable 'Log Violation Traffic' on the implicit deny to log it."),
    ("An FQDN address object can be used as source or destination in a firewall policy.", True,
     "FortiGate resolves the FQDN and updates the address list dynamically."),
    ("A schedule object defines when a firewall policy is active.", True,
     "Schedules can be one-time or recurring."),
    ("Flow-based inspection generally uses less memory and adds less latency than proxy-based inspection.", True,
     "That is its main advantage; proxy-based offers more features."),
]),

("NAT", [
    ("With NAT enabled in a policy and no IP pool selected, what is the source translated to?",
     ["*The outgoing interface IP address", "The incoming interface IP", "The first IP of the default pool", "Nothing, NAT needs a pool"],
     "Default SNAT uses the egress interface IP with port translation (PAT)."),
    ("Which IP pool type is the default?",
     ["*Overload", "One-to-One", "Fixed Port Range", "Port Block Allocation"],
     "Overload = many internal IPs share the pool IPs using PAT."),
    ("Which IP pool types exist? (Choose three)",
     ["*One-to-One", "*Fixed Port Range", "*Port Block Allocation", "Round Robin", "Dynamic Static"],
     "The four types are Overload, One-to-One, Fixed Port Range and Port Block Allocation."),
    ("Which object performs destination NAT on FortiGate?",
     ["*Virtual IP (VIP)", "IP pool", "Central SNAT rule", "Session helper"],
     "A VIP maps an external IP/port to an internal IP/port."),
    ("In policy NAT mode, how is a VIP applied?",
     ["*Select it as the destination address of the inbound policy",
      "Select it as the source address",
      "Enable it in the interface settings",
      "It is applied automatically without a policy"],
     "The inbound policy (external → internal) uses the VIP as destination."),
    ("What must you enable so that a deny policy blocks traffic destined to a VIP?",
     ["*`set match-vip enable`", "`set nat enable`", "`set vip-arp enable`", "Nothing, it is automatic"],
     "By default deny policies don't match VIP traffic."),
    ("In Central NAT mode, what destination do you use in the firewall policy for DNAT traffic?",
     ["*The real (mapped) internal address", "The VIP object", "The external IP", "`all` only"],
     "Central NAT uses the DNAT & Virtual IPs table; policies reference the mapped address."),
    ("Which feature opens related sessions and rewrites embedded addresses for protocols like FTP or SIP?",
     ["*Session helpers", "IP pools", "Central SNAT", "Hairpin NAT"],
     "Session helpers act as ALGs."),
    ("When Central SNAT is enabled, firewall policies no longer have a NAT option.", True,
     "SNAT is handled in the separate Central SNAT table, evaluated top-down."),
    ("A Fixed Port Range IP pool lets you trace a user from logs without logging each NAT session.", True,
     "Each internal IP maps to a fixed external IP and port range."),
    ("A static NAT VIP (no port forwarding) only translates inbound traffic.", False,
     "It is bidirectional: outbound traffic from the server uses the external IP when NAT is enabled."),
    ("A One-to-One IP pool maps each internal IP to its own external IP without port translation.", True,
     "When all pool IPs are in use, new internal IPs can't be translated."),
]),

("Firewall Authentication", [
    ("Which two methods are passive (transparent) authentication? (Choose two)",
     ["*FSSO", "*RSSO", "Captive portal", "Local user with password prompt"],
     "Passive methods learn identity without prompting the user."),
    ("Which protocols can trigger an active firewall authentication prompt? (Choose two)",
     ["*HTTP", "*FTP", "DNS", "ICMP"],
     "HTTP, HTTPS, FTP and Telnet can trigger the prompt."),
    ("Why must DNS be allowed for unauthenticated users with active authentication?",
     ["*So the browser can resolve names and send the HTTP request that triggers the prompt",
      "Because FortiGate authenticates users by DNS",
      "To download FortiGuard ratings",
      "It is not needed"],
     "Without DNS, no web request reaches FortiGate and no login page is shown."),
    ("What is the default firewall authentication timeout?",
     ["*10 minutes", "5 minutes", "30 minutes", "8 hours"],
     "`auth-timeout` 10; types: idle (default), hard, new-session."),
    ("Which LDAP bind type needs a username and password to search the directory?",
     ["*Regular", "Simple", "Anonymous", "Kerberos"],
     "Active Directory usually requires the Regular bind type."),
    ("Which common name identifier is typically used with Microsoft Active Directory?",
     ["*`sAMAccountName`", "`cn`", "`uid`", "`mail`"],
     "`cn` is common with generic LDAP servers."),
    ("Which command tests LDAP authentication for a user?",
     ["*`diagnose test authserver ldap <server> <user> <password>`",
      "`execute ldap test <user>`",
      "`diagnose debug authd fsso list`",
      "`get user ldap status`"],
     "It shows whether authentication succeeds and the user's groups."),
    ("Which port does the FSSO DC agent use to send logon events to the collector agent?",
     ["*UDP 8002", "TCP 8000", "TCP 8013", "UDP 514"],
     "The collector agent talks to FortiGate on TCP 8000."),
    ("Which command lists FSSO users known by FortiGate?",
     ["*`diagnose debug authd fsso list`", "`diagnose firewall auth list`", "`get user fsso`", "`diagnose sys session list`"],
     "`diagnose firewall auth list` shows firewall (active) authenticated users."),
    ("Which FSSO mode lets FortiGate poll domain controllers directly without any agent?",
     ["*Agentless polling mode", "DC agent mode", "Collector agent polling mode", "RSSO mode"],
     "Agentless polling is simpler but scales less."),
    ("RSSO learns user-to-IP mappings from RADIUS accounting messages.", True,
     "It is used with NAS devices, Wi-Fi controllers, VPN concentrators, etc."),
    ("To require authentication, you add a user or user group to the source of a firewall policy.", True,
     "The address is still required alongside the user/group."),
    ("FortiToken, email and SMS can be used as a second factor for local users.", True,
     "Remote users can use FortiToken too when configured locally as remote users."),
    ("In DC agent mode, the collector agent polls domain controller event logs.", False,
     "In DC agent mode, agents on each DC push logon events. Polling is the other mode."),
]),

("Certificates & SSL Inspection", [
    ("Which SSL inspection method only reads the SNI or server certificate?",
     ["*Certificate inspection", "Full SSL inspection", "Deep packet inspection", "Proxy inspection"],
     "It's enough for web filtering by domain but can't see URLs or content."),
    ("Which certificate does FortiGate use by default to re-sign trusted server certificates in deep inspection?",
     ["*`Fortinet_CA_SSL`", "`Fortinet_CA_Untrusted`", "`Fortinet_Factory`", "`Fortinet_Wifi`"],
     "Clients must trust it to avoid browser warnings."),
    ("Which certificate is used when the original server certificate is untrusted?",
     ["*`Fortinet_CA_Untrusted`", "`Fortinet_CA_SSL`", "`Fortinet_Factory`", "The original server certificate"],
     "This way the user still gets a warning, like without inspection."),
    ("Users see certificate warnings on every HTTPS site after you enable deep inspection. What is the fix?",
     ["*Install the FortiGate CA certificate as a trusted root on clients",
      "Switch the policy to flow-based",
      "Disable HTTPS administrative access",
      "Enable certificate inspection on port 80"],
     "Or use a subordinate CA signed by the enterprise PKI that clients already trust."),
    ("Why do some applications break under deep inspection?",
     ["*They use certificate pinning", "They use TCP port 443", "They use IPv6", "They use HTTP/1.1"],
     "Exempt them from inspection."),
    ("Which two are good reasons to exempt a site from deep inspection? (Choose two)",
     ["*Privacy or legal requirements (banking, health)", "*Applications with certificate pinning",
      "To enable web filtering", "To enable antivirus"],
     "Web filtering and AV need inspection, not exemption."),
    ("Which default SSL/SSH profile is read-only and decrypts traffic?",
     ["*`deep-inspection`", "`certificate-inspection`", "`no-inspection`", "`custom-deep-inspection`"],
     "Clone built-in profiles to customize them; `custom-deep-inspection` is editable."),
    ("Certificate inspection allows the FortiGate to see the full URL path of HTTPS requests.", False,
     "Only the domain (SNI/CN) is visible; full URLs need deep inspection."),
    ("Deep inspection is required for antivirus to scan files downloaded over HTTPS.", True,
     "Encrypted content can't be scanned."),
    ("A CSR is used to request a CA-signed certificate for FortiGate.", True,
     "For example for the admin GUI, VPN or a subordinate CA."),
]),

("Antivirus", [
    ("Which AV database contains the most signatures?",
     ["*Extreme", "Extended", "Normal", "Flow"],
     "Normal < Extended < Extreme (Extreme only on some models)."),
    ("What is the default action for files larger than the oversize limit?",
     ["*Pass them without scanning", "Block them", "Quarantine them", "Send them to FortiSandbox"],
     "You can change it to block in the protocol options profile."),
    ("Which feature removes macros and active content from Office/PDF files?",
     ["*Content Disarm and Reconstruction (CDR)", "Outbreak Prevention", "Grayware scanning", "Heuristics"],
     "CDR requires proxy-based inspection."),
    ("Which AV feature checks file hashes against FortiGuard and external hash lists?",
     ["*Outbreak Prevention", "CDR", "Grayware scanning", "Botnet scanning"],
     "It helps detect new threats before signatures exist."),
    ("Which three techniques does FortiGate AV use? (Choose three)",
     ["*Signature scanning", "*Grayware scanning", "*Heuristic / machine learning", "DNS filtering", "Traffic shaping"],
     "AV = virus signatures, grayware and heuristics (AI)."),
    ("In flow-based AV, how does FortiGate prevent an infected file from reaching the client?",
     ["*It holds the last packet until the scan result is known",
      "It buffers the whole file before forwarding anything",
      "It resets the connection at the first packet",
      "It can't block files in flow mode"],
     "Packets are forwarded while the file is cached; the last one is released only if clean."),
    ("What does integrating FortiSandbox add to FortiGate AV?",
     ["*Detection of zero-day malware by running files in a sandbox",
      "Faster signature updates",
      "SSL decryption",
      "Web category ratings"],
     "FortiSandbox can also return dynamic signatures."),
    ("Proxy-based AV buffers the entire file before scanning it.", True,
     "That's why it adds more latency than flow-based."),
    ("CDR works in flow-based inspection mode.", False,
     "CDR needs proxy-based inspection."),
    ("When AV blocks an HTTP download, the user sees a replacement message page.", True,
     "Replacement messages can be customized."),
]),

("Web Filtering & DNS Filtering", [
    ("Which web filter check is applied first?",
     ["*Static URL filter", "FortiGuard category filter", "Content filter", "Antivirus"],
     "Then FortiGuard categories, then content/advanced filters."),
    ("Which action lets the user continue to a site after a warning page?",
     ["*Warning", "Monitor", "Authenticate", "Block"],
     "The user can click through for a configured time."),
    ("What does the 'Exempt' action in the static URL filter do?",
     ["*Allows the URL and skips the remaining web filter checks",
      "Blocks the URL",
      "Logs the URL only",
      "Requires user authentication"],
     "Exempt can also skip AV and other scans."),
    ("Which pattern types does the static URL filter support? (Choose three)",
     ["*Simple", "*Wildcard", "*Regular expression", "Category", "Geography"],
     "Categories are FortiGuard filtering, not static URL filter."),
    ("How do you move a URL to a different category only on your FortiGate?",
     ["*Create a web rating override", "Submit it to FortiGuard", "Use DNS filter", "Add it to an address group"],
     "You can also create custom local categories."),
    ("Which command checks the FortiGuard web filter server list and connectivity?",
     ["*`diagnose debug rating`", "`diagnose autoupdate versions`", "`execute ping fortiguard.com`", "`get webfilter status`"],
     "It shows servers, weight, RTT and packet loss."),
    ("What is an advantage of DNS filtering over web filtering?",
     ["*It is light and works without SSL inspection",
      "It can scan file content",
      "It can see full URLs",
      "It can block specific YouTube videos"],
     "It filters the DNS query before any connection happens."),
    ("What does DNS filter return by default for a blocked domain?",
     ["*A redirect to the FortiGuard block portal IP", "An NXDOMAIN only", "The real IP with a warning", "No response"],
     "You can also set a custom redirect IP."),
    ("DNS filter can block access to known botnet command-and-control domains.", True,
     "It uses the FortiGuard botnet C&C domain list."),
    ("FortiGate sends URL rating queries to FortiGuard and caches the results.", True,
     "The cache reduces lookups and latency."),
    ("The 'Monitor' action blocks the site and logs it.", False,
     "Monitor allows the site and logs it."),
]),

("Application Control", [
    ("Which engine does Application Control use to identify applications?",
     ["*IPS engine", "Proxy engine", "Web filter engine", "DNS engine"],
     "App signatures run in the IPS engine and don't depend on port numbers."),
    ("What is the order of precedence in an Application Control profile?",
     ["*Application overrides → filter overrides → categories",
      "Categories → filter overrides → application overrides",
      "Filter overrides → categories → application overrides",
      "They all have the same priority"],
     "The most specific setting wins."),
    ("Which action is NOT available in Application Control?",
     ["*Warning", "Monitor", "Block", "Quarantine"],
     "Warning is a web filter action."),
    ("Why is deep inspection often needed for Application Control?",
     ["*To tell apart applications and sub-features inside HTTPS",
      "To identify apps by port",
      "Because Application Control only works in proxy mode",
      "To download signatures"],
     "Many apps use HTTPS; decryption gives full visibility."),
    ("Which option blocks HTTP running on port 8080?",
     ["*Block applications detected on non-default ports", "Allow DNS traffic", "Replacement messages for HTTP-based applications", "Enable QUIC inspection"],
     "It blocks known apps that run on non-standard ports."),
    ("Application Control can identify applications regardless of the port they use.", True,
     "Signatures match traffic patterns, not ports."),
    ("Application overrides have lower priority than categories.", False,
     "Application overrides have the highest priority."),
    ("You can apply traffic shaping to specific applications.", True,
     "Using traffic shaping policies or application-based shapers."),
]),

("Intrusion Prevention & DoS", [
    ("Which three detection methods does FortiGate IPS use? (Choose three)",
     ["*Signatures", "*Protocol decoders", "*Anomaly detection", "URL categories", "Heuristic AV"],
     "Anomaly detection is done with DoS policies."),
    ("When is a DoS policy processed?",
     ["*Before the firewall policy lookup", "After the firewall policy", "Only after authentication", "Only on outgoing interfaces"],
     "DoS policies drop attacks early, on the incoming interface."),
    ("Which is a DoS anomaly that limits the number of sessions from one source?",
     ["*`ip_src_session`", "`tcp_syn_flood`", "`icmp_sweep`", "`udp_flood`"],
     "`ip_dst_session` limits sessions per destination."),
    ("What does IPS fail-open do?",
     ["*Lets traffic pass uninspected when the IPS engine is overloaded",
      "Blocks all traffic when the IPS engine fails",
      "Opens all ports",
      "Disables IPS signatures"],
     "`set fail-open enable` favors availability over security."),
    ("Which action sends TCP resets to both client and server?",
     ["*Reset", "Block", "Monitor", "Pass"],
     "Block silently drops packets."),
    ("What are rate-based IPS signatures used for?",
     ["*Detecting attacks by number of matches in a time window, such as brute force",
      "Limiting bandwidth",
      "Rating web sites",
      "Measuring latency"],
     "They trigger only when the threshold is reached."),
    ("Which command can restart the IPS engines?",
     ["*`diagnose test application ipsmonitor`", "`execute ips restart`", "`diagnose ips reset`", "`execute update-ips`"],
     "Option 99 restarts all IPS engines."),
    ("DoS policies are applied after firewall policies.", False,
     "They are applied before, on the ingress interface."),
    ("An IPS signature set to 'Default' uses the action recommended by FortiGuard.", True,
     "Each signature has a default action (pass or block)."),
    ("IPS can detect exploits inside HTTPS without SSL deep inspection.", False,
     "Most exploits are inside the encrypted payload and need decryption."),
]),

("Security Fabric", [
    ("What is required, besides the root FortiGate, to build a Security Fabric?",
     ["*FortiAnalyzer or cloud logging", "FortiManager", "FortiSandbox", "FortiClient EMS"],
     "FortiAnalyzer (or FortiAnalyzer Cloud / FortiGate Cloud) is mandatory."),
    ("Which port do downstream FortiGates use to connect to the upstream FortiGate?",
     ["*TCP 8013", "TCP 541", "TCP 514", "UDP 8002"],
     "Enable 'Security Fabric Connection' on the upstream interface."),
    ("What are the two parts of an automation stitch? (Choose two)",
     ["*Trigger", "*Action", "Schedule group", "Address group"],
     "For example: trigger = compromised host, action = quarantine."),
    ("What does the Security Rating provide?",
     ["*Audit checks with scores and recommendations",
      "Web site categories",
      "IPS signature ratings",
      "User risk scores only"],
     "Checks cover security posture, fabric coverage and optimization."),
    ("What do Fabric connectors provide?",
     ["*Integration with external systems and dynamic address objects",
      "Physical cables between FortiGates",
      "VPN tunnels",
      "HA heartbeat links"],
     "For example public cloud SDN, threat feeds and FSSO."),
    ("The root FortiGate is the top of the Security Fabric tree.", True,
     "Downstream devices connect to it directly or through other FortiGates."),
    ("An automation stitch can only send emails.", False,
     "Actions include quarantine, CLI script, webhook, email, FortiClient actions, etc."),
]),

("Routing", [
    ("What is the first criterion FortiGate uses to select a route?",
     ["*Longest prefix match", "Lowest distance", "Lowest priority", "Lowest metric"],
     "Then administrative distance, then priority (static routes)."),
    ("What is the default administrative distance of a static route?",
     ["*10", "1", "20", "110"],
     "Connected 0, static 10, eBGP 20, OSPF 110, RIP 120, iBGP 200."),
    ("Which route source has the highest (least preferred) default distance?",
     ["*iBGP (200)", "RIP (120)", "OSPF (110)", "eBGP (20)"],
     "Lower distance is preferred."),
    ("Two static routes to 0.0.0.0/0 have the same distance but priorities 1 and 5. What happens?",
     ["*Both are in the routing table; the priority 1 route is used",
      "Only the priority 5 route is in the table",
      "Traffic is load-balanced (ECMP)",
      "Only the first created route is used"],
     "Priority is a tie-breaker; both routes stay active."),
    ("Which command shows inactive routes too?",
     ["*`get router info routing-table database`", "`get router info routing-table all`", "`diagnose ip route list`", "`show router static`"],
     "The routing table (FIB) only shows active best routes."),
    ("Which is checked first when forwarding a new session?",
     ["*Policy routes", "Routing table", "SD-WAN implicit rule", "ARP table"],
     "A matching policy route overrides the routing table."),
    ("What is the default ECMP load balancing method?",
     ["*Source IP based", "Weighted", "Usage (spillover)", "Round robin per packet"],
     "Others: source-destination IP, weighted, usage."),
    ("What is the purpose of the RPF check?",
     ["*Anti-spoofing: verify the source is reachable through the incoming interface",
      "Pick the best route",
      "Detect routing loops in OSPF",
      "Check the route to FortiGuard"],
     "Loose by default; strict mode requires the best route to be through that interface."),
    ("What does a link health monitor do when its probes fail?",
     ["*Removes the related static routes from the routing table", "Reboots the interface", "Disables the firewall policy", "Sends an SNMP trap only"],
     "Traffic then fails over to a backup route."),
    ("What is a blackhole route used for?",
     ["*Silently dropping traffic to a destination", "Load balancing", "Routing to a VPN", "Routing to the management VDOM"],
     "Common to avoid leaking private traffic to the Internet when a VPN is down."),
    ("If two routes have the same prefix, distance and priority, FortiGate uses ECMP.", True,
     "Traffic is shared between the routes using the ECMP method."),
    ("Connected routes have an administrative distance of 0.", True,
     "They are always preferred over routes with the same prefix."),
    ("The routing table contains routes that are not currently active.", False,
     "Inactive routes are only in the routing database."),
]),

("SD-WAN", [
    ("What is the name of the default SD-WAN zone?",
     ["*`virtual-wan-link`", "`sdwan-zone`", "`wan-default`", "`root`"],
     "Additional zones can be created."),
    ("Which three metrics can a performance SLA measure? (Choose three)",
     ["*Latency", "*Jitter", "*Packet loss", "Bandwidth usage", "CPU usage"],
     "Probes: ping, HTTP, DNS, TCP echo, etc."),
    ("Which SD-WAN rule strategy picks the link with the best measured metric?",
     ["*Best Quality", "Manual", "Lowest Cost (SLA)", "Maximize Bandwidth (SLA)"],
     "Lowest Cost chooses the cheapest link that meets the SLA."),
    ("What happens when no SD-WAN rule matches?",
     ["*The implicit rule uses the routing table / load balancing", "Traffic is dropped", "The first member is used", "Traffic goes through the management interface"],
     "The implicit rule's default method is source-IP."),
    ("What is needed so traffic can use SD-WAN?",
     ["*A route (e.g. default route) pointing to the SD-WAN zone", "A VIP", "An IP pool", "A DoS policy"],
     "Plus a firewall policy with the SD-WAN zone as outgoing interface."),
    ("SD-WAN rules are evaluated top to bottom and the first match is used.", True,
     "The implicit rule is always at the bottom."),
    ("In firewall policies you should reference each SD-WAN member interface instead of the SD-WAN zone.", False,
     "Use the zone so that the policy works whatever member is chosen."),
    ("Maximize Bandwidth (SLA) load-balances traffic across all members that meet the SLA.", True,
     "Members out of SLA are excluded."),
]),

("IPsec VPN", [
    ("What does IKE phase 1 establish?",
     ["*The IKE SA: peer authentication and a secure channel", "The IPsec SAs for data", "The routes to the remote network", "The firewall policies"],
     "Phase 2 then builds the IPsec SAs."),
    ("Which ports/protocols does IPsec use? (Choose three)",
     ["*UDP 500", "*UDP 4500", "*ESP (IP protocol 50)", "TCP 443", "TCP 8013"],
     "UDP 4500 is used for NAT traversal."),
    ("How many messages does IKEv1 aggressive mode use?",
     ["*3", "6", "2", "4"],
     "Main mode uses 6 and protects the identity."),
    ("When is aggressive mode needed?",
     ["*To tell apart multiple dial-up peers by peer ID with a pre-shared key", "For all site-to-site VPNs", "For IKEv2", "When using certificates only"],
     "The peer ID is sent in the first message."),
    ("What must match on both peers for phase 2 to come up? (Choose two)",
     ["*Quick mode selectors (local/remote subnets)", "*Phase 2 proposals", "Tunnel interface names", "Firewall policy IDs"],
     "PFS and DH groups must also match."),
    ("Besides the tunnel, what does a route-based site-to-site VPN need? (Choose two)",
     ["*A route to the remote subnet through the tunnel interface", "*Firewall policies between LAN and tunnel", "A VIP", "An IP pool"],
     "Usually policies in both directions."),
    ("What is Dead Peer Detection (DPD)?",
     ["*Keepalives that detect an unreachable peer and clear the SAs", "An IPS signature", "A routing protocol", "Anti-replay protection"],
     "Modes: on-idle (default), on-demand, disabled."),
    ("Which command shows IPsec phase 2 tunnels and traffic counters?",
     ["*`diagnose vpn tunnel list`", "`diagnose vpn ike gateway list`", "`get router info routing-table all`", "`diagnose sys session list`"],
     "`diagnose vpn ike gateway list` shows phase 1."),
    ("Which command starts the IKE real-time debug?",
     ["*`diagnose debug application ike -1` then `diagnose debug enable`", "`diagnose sniffer packet any 'port 500'`", "`execute vpn debug`", "`get vpn ike status`"],
     "Filter first with `diagnose vpn ike log-filter`."),
    ("What does IKE mode config provide?",
     ["*IP address, DNS and split-tunnel settings to dial-up clients", "Firewall policies", "Routing protocol settings", "Certificates"],
     "Used for FortiClient remote access."),
    ("Route-based (interface mode) VPN is the recommended type on FortiGate.", True,
     "It supports routing protocols, SD-WAN and redundancy."),
    ("In a dial-up VPN, the hub can initiate the tunnel to the remote peer.", False,
     "The remote peer has a dynamic IP, so only the remote side can initiate."),
    ("Anti-replay drops ESP packets with duplicate or old sequence numbers.", True,
     "It protects against replay attacks."),
]),

("SSL VPN & ZTNA", [
    ("Which interface is the incoming interface of an SSL VPN firewall policy?",
     ["*`ssl.root`", "`port1`", "`any`", "`sslvpn0`"],
     "`ssl.<vdom>` in other VDOMs."),
    ("What are the two SSL VPN modes? (Choose two)",
     ["*Web mode", "*Tunnel mode", "Transparent mode", "NAT mode"],
     "Web mode uses a browser portal; tunnel mode uses FortiClient."),
    ("With split tunneling enabled, which traffic goes through the SSL VPN?",
     ["*Only traffic to the protected networks", "All client traffic", "Only DNS", "Only web traffic"],
     "With full tunnel, all traffic goes through FortiGate."),
    ("What must be in the source of the SSL VPN firewall policy?",
     ["*The SSL VPN user or user group", "A VIP", "The ISDB", "An IP pool"],
     "Along with the SSL VPN tunnel address range."),
    ("What does ZTNA use to decide access?",
     ["*User identity and device posture (ZTNA tags)", "Only source IP", "Only the SSL VPN portal", "Only the MAC address"],
     "Access is granted per application."),
    ("Which product provides ZTNA tags and device certificates?",
     ["*FortiClient EMS", "FortiAnalyzer", "FortiManager", "FortiSandbox"],
     "EMS manages FortiClient endpoints."),
    ("SSL VPN web mode requires FortiClient on the endpoint.", False,
     "Web mode only needs a browser."),
    ("In recent FortiOS versions, IPsec VPN or ZTNA is recommended over SSL VPN tunnel mode.", True,
     "SSL VPN tunnel mode is being phased out in FortiOS 7.6+."),
]),

("High Availability", [
    ("What are the two FGCP modes? (Choose two)",
     ["*Active-Passive", "*Active-Active", "Standalone session sync", "Active-Standby-Witness"],
     "FGSP is a separate protocol for session sync between peers."),
    ("With override disabled (default), what is the primary election order?",
     ["*Monitored interfaces → HA uptime → priority → serial number",
      "Priority → HA uptime → monitored interfaces → serial number",
      "Monitored interfaces → priority → HA uptime → serial number",
      "Serial number → priority → HA uptime"],
     "With override enabled, priority comes before HA uptime."),
    ("With override enabled, what is the primary election order?",
     ["*Monitored interfaces → priority → HA uptime → serial number",
      "Monitored interfaces → HA uptime → priority → serial number",
      "Priority → serial number → HA uptime",
      "HA uptime → priority → monitored interfaces"],
     "Override makes the highest priority unit always become primary."),
    ("Below what HA uptime difference does FortiGate ignore uptime in the election?",
     ["*5 minutes (300 s)", "1 minute", "10 minutes", "1 hour"],
     "`ha-uptime-diff-margin` default 300 s."),
    ("Which three must match for an FGCP cluster? (Choose three)",
     ["*Model and firmware", "*Group ID/name and password", "*HA mode", "Hostname", "Management IP"],
     "Licenses should also match."),
    ("How does the network learn about the new primary after failover?",
     ["*Gratuitous ARPs with the virtual MAC addresses", "OSPF update", "DHCP renewal", "DNS update"],
     "Cluster interfaces use virtual MACs."),
    ("In Active-Active, which sessions are load-balanced by default?",
     ["*Sessions inspected by security profiles", "All TCP sessions", "All UDP sessions", "Only VPN sessions"],
     "Enable `load-balance-all` to include all TCP sessions."),
    ("Which command checks that the configuration is in sync in the cluster?",
     ["*`diagnose sys ha checksum cluster`", "`get system ha status`", "`execute ha synchronize`", "`diagnose sys top`"],
     "Matching checksums mean the configs are synced."),
    ("Which command opens the CLI of a secondary unit from the primary?",
     ["*`execute ha manage <index> <admin>`", "`execute ssh secondary`", "`config ha secondary`", "`diagnose sys ha connect`"],
     "Use `execute ha manage ?` to list the indexes."),
    ("Session pickup is enabled by default in FGCP.", False,
     "Enable `session-pickup` to sync sessions for seamless failover."),
    ("FGSP synchronizes sessions between standalone FortiGates.", True,
     "It is often used behind external load balancers."),
    ("A reserved management interface keeps its own IP on each cluster member.", True,
     "It allows direct management and monitoring of each unit."),
    ("Heartbeat interfaces carry HA hello packets, configuration sync and session sync.", True,
     "Use at least two heartbeat links for redundancy."),
]),

("Virtual Domains (VDOMs)", [
    ("What is the management VDOM used for?",
     ["*FortiGate's own traffic: FortiGuard updates, logging, NTP", "User traffic only", "HA heartbeat", "Inter-VDOM routing"],
     "It is `root` by default."),
    ("What are the two VDOMs in split-task VDOM mode? (Choose two)",
     ["*`root`", "*`FG-traffic`", "`mgmt`", "`global`"],
     "`root` for management, `FG-traffic` for user traffic."),
    ("How do two VDOMs exchange traffic internally?",
     ["*Inter-VDOM links", "Zones", "Software switch", "VIPs"],
     "Routes and firewall policies are still needed."),
    ("Which setting is global (not per VDOM)?",
     ["*HA configuration", "Firewall policies", "Static routes", "Security profiles"],
     "Also firmware, FortiGuard and admin accounts."),
    ("How many VDOMs do most models support without an extra license?",
     ["*10", "5", "25", "Unlimited"],
     "Larger models can add VDOM licenses."),
    ("Each VDOM has its own routing table and firewall policies.", True,
     "A VDOM behaves like a separate FortiGate."),
    ("An interface can belong to several VDOMs at the same time.", False,
     "Each interface belongs to exactly one VDOM."),
]),

("Layer 2 & Transparent Mode", [
    ("In transparent mode, the FortiGate acts as:",
     ["*A Layer 2 bridge", "A router", "A proxy server", "A VPN concentrator only"],
     "It inspects traffic without changing IP addressing."),
    ("What IP configuration does a transparent mode VDOM need?",
     ["*A management IP and gateway", "An IP on every interface", "No IP at all", "A VIP"],
     "Used for administration and FortiGuard updates."),
    ("What limits where broadcasts are flooded in transparent mode?",
     ["*Forwarding domains", "Zones", "VLAN pools", "IP pools"],
     "Set with `forward-domain` on interfaces."),
    ("Which switch type can include a Wi-Fi SSID as a member?",
     ["*Software switch", "Hardware switch", "Both", "Neither"],
     "A software switch is handled by the CPU."),
    ("A FortiGate in transparent mode still applies firewall policies and security profiles.", True,
     "Only routing and NAT features differ."),
    ("A hardware switch uses the switch chip and is faster than a software switch.", True,
     "But it only supports specific physical ports."),
]),

("Logging & Monitoring", [
    ("Which three are the main FortiGate log types? (Choose three)",
     ["*Traffic", "*Event", "*Security", "Session", "Debug"],
     "Security logs include AV, web filter, IPS, application control, etc."),
    ("Which protocol and port does FortiGate use to send logs to FortiAnalyzer?",
     ["*OFTP, TCP 514", "Syslog, UDP 514", "HTTPS, TCP 443", "SNMP, UDP 162"],
     "OFTP is encrypted by default."),
    ("Which log severity is the most severe?",
     ["*Emergency", "Alert", "Critical", "Error"],
     "Emergency, Alert, Critical, Error, Warning, Notification, Information, Debug."),
    ("Which traffic log subtype records traffic to or from the FortiGate itself?",
     ["*Local", "Forward", "Sniffer", "Event"],
     "Forward = traffic through the FortiGate."),
    ("What is threat weight used for?",
     ["*Scoring security events to rank risky users and devices", "Limiting bandwidth", "Choosing SD-WAN links", "HA election"],
     "Visible in FortiView."),
    ("Why do some small models disable local disk logging?",
     ["*To protect flash storage life", "Because of licensing", "Because of HA", "Because disk logs aren't encrypted"],
     "Log to FortiAnalyzer or the cloud instead."),
    ("A policy must log allowed traffic for its security profile events to be logged.", True,
     "Set Log Allowed Traffic to Security Events or All Sessions."),
    ("Logs can be sent to FortiAnalyzer and to a syslog server at the same time.", True,
     "Several remote log destinations can be configured."),
]),

("Diagnostics & Troubleshooting", [
    ("Which command starts tracing 10 packets in a debug flow?",
     ["*`diagnose debug flow trace start 10`", "`diagnose sniffer packet any '' 4 10`", "`diagnose debug enable 10`", "`execute trace 10`"],
     "Set a filter and `diagnose debug enable` first."),
    ("Which debug flow message shows traffic dropped by the implicit deny?",
     ["*`Denied by forward policy check (policy 0)`", "`reverse path check fail`", "`no session matched`", "`iprope_in_check() check failed`"],
     "`reverse path check fail` means an RPF drop."),
    ("Which sniffer verbosity adds the interface name to each packet?",
     ["*4", "1", "2", "3"],
     "6 adds the interface, Ethernet header and hex data."),
    ("In `diagnose sniffer packet any 'host 8.8.8.8' 4 10 a`, what does `a` do?",
     ["*Shows absolute timestamps", "Captures all interfaces", "Shows ASCII data", "Captures ARP only"],
     "`l` gives local time."),
    ("At what memory usage does FortiGate enter conserve mode by default?",
     ["*88%", "70%", "82%", "95%"],
     "Extreme conserve mode at 95%; exits below 82%."),
    ("What is the default `av-failopen` behavior during conserve mode?",
     ["*`pass`", "`off`", "`one-shot`", "`block`"],
     "`off` blocks new sessions needing proxy inspection."),
    ("Which command shows CPU, memory and session usage?",
     ["*`get system performance status`", "`get system status`", "`diagnose sys session list`", "`diagnose hardware deviceinfo nic`"],
     "`diagnose sys top` shows per-process usage."),
    ("Which command shows firmware version, serial number and operation mode?",
     ["*`get system status`", "`get system performance status`", "`diagnose autoupdate versions`", "`show system global`"],
     "It also shows VDOM mode and HA status."),
    ("What do NP processors offload?",
     ["*Firewall and IPsec session forwarding", "AV signature matching", "Log storage", "GUI processing"],
     "CP processors accelerate encryption and content inspection."),
    ("Which command shows interface speed, duplex and errors?",
     ["*`diagnose hardware deviceinfo nic <port>`", "`get system interface`", "`diagnose sys top`", "`execute interface status`"],
     "Look for CRC and error counters."),
    ("Which command sets the source IP for `execute ping`?",
     ["*`execute ping-options source <ip>`", "`execute ping -s <ip>`", "`set ping-source <ip>`", "`diagnose ping source <ip>`"],
     "Useful to test VPN traffic from a LAN IP."),
    ("`diagnose debug reset` and `diagnose debug disable` stop debug output.", True,
     "Always stop debugs after troubleshooting."),
    ("The packet sniffer can only capture on one interface at a time.", False,
     "Use `any` to capture on all interfaces."),
    ("In conserve mode, FortiGate may stop accepting new sessions that need proxy inspection.", True,
     "Depending on `av-failopen`."),
]),
]
